import fp from 'fastify-plugin';
import type { FastifyPluginAsync } from 'fastify';

/**
 * Sets `X-Request-Id` on every response. The actual ID is generated by
 * Fastify's `genReqId` (configured to use ULID at server build time).
 */
const requestIdPlugin: FastifyPluginAsync = async (app) => {
  app.addHook('onSend', async (req, reply, payload) => {
    if (!reply.getHeader('x-request-id')) {
      reply.header('x-request-id', req.id);
    }
    return payload;
  });
};

export default fp(requestIdPlugin, { name: 'request-id' });
