#!/usr/bin/env bash
# ──────────────────────────────────────────────────────────────────────
# scripts/deploy.sh
#
# Generates production secrets and writes two ready-to-paste env files:
#
#   .env.production.railway   →  paste into Railway → Variables → Raw Editor
#   .env.production.vercel    →  paste into Vercel  → Settings → Environment Variables → Import .env
#
# Both files are gitignored. Re-running this script keeps the existing
# secrets (idempotent) — it only fills in placeholder URLs you replace
# after the platforms hand you domains.
# ──────────────────────────────────────────────────────────────────────
set -euo pipefail

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

SECRETS_FILE="$ROOT/.env.deploy.local"
RAILWAY_ENV="$ROOT/.env.production.railway"
VERCEL_ENV="$ROOT/.env.production.vercel"

# ── 1. Secrets (only generated once; reused on subsequent runs) ──────
if [[ ! -f "$SECRETS_FILE" ]]; then
  echo "→ Generating production secrets…"
  cat > "$SECRETS_FILE" << EOF
# AUTO-GENERATED — do not commit, do not paste anywhere except Railway.
# Three distinct secrets so a leak in one domain (CSM access) doesn't
# compromise the others (chat URL token / chat session JWT).
JWT_ACCESS_SECRET=$(openssl rand -base64 48 | tr -d '\n' | head -c 64)
SESSION_TOKEN_SECRET=$(openssl rand -base64 48 | tr -d '\n' | head -c 64)
SESSION_JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n' | head -c 64)
EOF
  chmod 600 "$SECRETS_FILE" 2>/dev/null || true
  echo "  ✓ secrets written to $SECRETS_FILE (gitignored, 0600)"
else
  echo "→ Reusing existing secrets from $SECRETS_FILE"
fi

# Load the secrets into this shell.
set -a
# shellcheck source=/dev/null
source "$SECRETS_FILE"
set +a

# ── 2. Railway env file ──────────────────────────────────────────────
cat > "$RAILWAY_ENV" << EOF
# Generated by scripts/deploy.sh. Paste the contents of this file into:
#   Railway → API service → Variables → "Raw Editor" → save.
# Replace the YOUR-*-DOMAIN placeholders after both Railway and Vercel
# hand you live domains, then click "Save" again to redeploy.

NODE_ENV=production
LOG_LEVEL=info

# Railway injects PORT automatically — Fastify already reads it.
# DATABASE_URL is provided by the Postgres add-on. Use the reference:
DATABASE_URL=\${{Postgres.DATABASE_URL}}
DATABASE_POOL_MAX=10
DATABASE_POOL_IDLE_TIMEOUT_MS=30000

# JWT secrets — three distinct values.
JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
JWT_ACCESS_TTL_SEC=900
JWT_REFRESH_TTL_DAYS=30
SESSION_TOKEN_SECRET=${SESSION_TOKEN_SECRET}
SESSION_JWT_SECRET=${SESSION_JWT_SECRET}
SESSION_JWT_TTL_SEC=3600

# Cookies (production).
COOKIE_SECURE=true
COOKIE_SAMESITE=lax

# Domains — replace these once Railway + Vercel give you URLs.
APP_BASE_URL=https://YOUR-VERCEL-DOMAIN.vercel.app
API_BASE_URL=https://YOUR-RAILWAY-DOMAIN.up.railway.app
CORS_ORIGINS=https://YOUR-VERCEL-DOMAIN.vercel.app

# WebSocket heartbeat.
WS_PING_INTERVAL_MS=25000
WS_PING_TIMEOUT_MS=60000

# Sentry (optional — leave blank to disable error reporting).
SENTRY_ENVIRONMENT=production
SENTRY_DSN_API=
EOF

# ── 3. Vercel env file ───────────────────────────────────────────────
cat > "$VERCEL_ENV" << EOF
# Generated by scripts/deploy.sh. Paste the contents of this file into:
#   Vercel → Project → Settings → Environment Variables → "Import .env"
#   (or paste each line into the bulk editor).
# Replace the YOUR-RAILWAY-DOMAIN placeholder after Railway gives you a URL.

NEXT_PUBLIC_API_URL=https://YOUR-RAILWAY-DOMAIN.up.railway.app
NEXT_PUBLIC_WS_URL=wss://YOUR-RAILWAY-DOMAIN.up.railway.app
NEXT_PUBLIC_SENTRY_DSN=
EOF

cat << 'EOF'

✓ Done.

Next steps — about 6 clicks each:

  RAILWAY (API)
  1. railway.app → New Project → Database → PostgreSQL
  2. + New → GitHub Repo → pick the chat repo (railway.json picks the Dockerfile)
  3. Service → Variables → "Raw Editor" → paste the file: .env.production.railway
  4. Save. Railway will deploy. Note the railway.app domain it gives you.
  5. Service → "..." → "Run Command" →
       pnpm --filter @csm-chat/db db:migrate
       pnpm --filter @csm-chat/db db:seed
     (Watch the seed banner; change the seeded admin password later.)

  VERCEL (Web)
  1. vercel.com → Add New → Project → import the chat repo
  2. Root Directory → "apps/web"
  3. Settings → Environment Variables → "Import .env" → upload: .env.production.vercel
  4. Replace YOUR-RAILWAY-DOMAIN with the Railway URL you noted in step 4 above
  5. Deploy. Note the .vercel.app domain.

  WIRE THEM TOGETHER
  6. Back in Railway Variables → Raw Editor:
       APP_BASE_URL=https://<your vercel domain>
       CORS_ORIGINS=https://<your vercel domain>
       API_BASE_URL=https://<your railway domain>
     Save. Railway redeploys.

  SMOKE TEST
       API_URL=https://<your railway domain> \
       SEED_PASSWORD='Admin123!@#456' \
         ./scripts/smoke.sh

EOF
